export const DIFF_EMPTY_CODE_HEIGHT = 96
export const DIFF_FILE_HEADER_HEIGHT = 42
export const DIFF_LINE_HEIGHT_PX = 20
export const DIFF_MIN_HUNK_CONTEXT_LINES = 4
export const DIFF_MIN_RENDERED_LINES = 6
export const DIFF_RENDERED_LINES_PER_HUNK = 6
